// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2lW1shHX47FegOAWLxtAN6OYLq7iVP6Q',
    appId: '1:439060117531:web:c75d76a6e8b241480b60be',
    messagingSenderId: '439060117531',
    projectId: 'hackathon-fd750',
    authDomain: 'hackathon-fd750.firebaseapp.com',
    storageBucket: 'hackathon-fd750.firebasestorage.app',
    measurementId: 'G-VS2G4360L1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwvRX91iSCDuyn5TenRMH0qmMmnqAf6vg',
    appId: '1:439060117531:android:f3342551953e5f9f0b60be',
    messagingSenderId: '439060117531',
    projectId: 'hackathon-fd750',
    storageBucket: 'hackathon-fd750.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBw5kUAfP3Qf3x2sPCgBm1vA4vSZszk4YA',
    appId: '1:439060117531:ios:a123414dbb5fdb360b60be',
    messagingSenderId: '439060117531',
    projectId: 'hackathon-fd750',
    storageBucket: 'hackathon-fd750.firebasestorage.app',
    iosBundleId: 'com.example.budgetbuddy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBw5kUAfP3Qf3x2sPCgBm1vA4vSZszk4YA',
    appId: '1:439060117531:ios:a123414dbb5fdb360b60be',
    messagingSenderId: '439060117531',
    projectId: 'hackathon-fd750',
    storageBucket: 'hackathon-fd750.firebasestorage.app',
    iosBundleId: 'com.example.budgetbuddy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2lW1shHX47FegOAWLxtAN6OYLq7iVP6Q',
    appId: '1:439060117531:web:f8ecf0a88932537a0b60be',
    messagingSenderId: '439060117531',
    projectId: 'hackathon-fd750',
    authDomain: 'hackathon-fd750.firebaseapp.com',
    storageBucket: 'hackathon-fd750.firebasestorage.app',
    measurementId: 'G-44XKJQXQ1Q',
  );
}
